[project]
name = "readme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pendulum>=3.1.0",
    "spotipy>=2.25.1",
]
