on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  readme:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.12"
      - name: "Install dependencies"
        run: "pip install --requirement requirements.txt"
      - name: "Query GitHub API"
        run: "python query.py"
      - name: "Update table in README"
        run: "python readme.py"
      - uses: "stefanzweifel/git-auto-commit-action@v5"
