on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  readme:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
          cache: "pip"
      - name: "Install dependencies"
        run: "pip install --requirement requirements.txt"
      - name: "Generate new README.md"
        run: "python generate.py"
      - uses: "stefanzweifel/git-auto-commit-action@v5"
        with:
          commit_message: "chore: update readme"
